### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by pereverti**
Correct lot of mistakes 

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
I must close this as well, but don't worry. Your efforts will not be lost. Tonight I will update the French files and make sure you get the credit for them :-).

Thanks again for fixing these error, I am happy that you wish to help

**Comment by pereverti** [comment]
No problem for the credits it's not important. I just want to improve the french translation and FF in general :-)
Sorry for my bad commits I forgot some \ and '

For other files, I will use Crowdin I promess :D

**Comment by JC5** [comment]
I've updated them all :+1:

**Comment by pereverti** [comment]
Thank you very much :-)
I'll continue on Crowdin.

**Pull request closed without merging**
