### PR TITLE
add test cases for api/v1/autocomplete/CategoryController

### PR DESCRIPTION
**Pull request by tasnim0tantawi**
I'm trying to improve the test coverage of the project. Will add more tests for autocomplete.

image

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Nice work! Make sure you change the copyright notice to the actual year and your name or GitHub name :)

**Comment by tasnim0tantawi** [comment]
> Nice work! Make sure you change the copyright notice to the actual year and your name or GitHub name :)

@JC5 Thanks so much! Done!
I will be doing tests for the rest of controllers.

**Review by JC5 — APPROVED** [review]

**Comment by JC5** [comment]
I'm aware the tests are failing, I have another test to fix first.

**Comment by tasnim0tantawi** [comment]
> I'm aware the tests are failing, I have another test to fix first.

@JC5 It is only one. I will try to check it!

**Comment by tasnim0tantawi** [comment]
> > I'm aware the tests are failing, I have another test to fix first.
> 
> @JC5 It is only one. I will try to check it!

image

Fixed ! Will do a PR right now

**Pull request merged**
