### PR TITLE
Add username to fit redis 6+ ACL capabilities

### PR DESCRIPTION
**Pull request by canoine**
This just adds the ability to set a redis username.

### CODE REVIEW

**Comment by JC5** [comment]
Looks good. However, when it's empty or NULL, the config file will fallback to "default", even though your instructions say:

> Use only with Redis 6+ with proper ACL set. Leave empty otherwise.

Shouldn't that be `env('REDIS_USERNAME')`?

**Comment by canoine** [comment]
You're right. Even more, perhaps forcing a default username will break the compatibility with Redis before 6.0.0.
I'll change the PR (sorry for the noise, I'm a beginner).

**Comment by JC5** [comment]
Nice work, don't worry about the noise. As a final touch, could you change the password field in the .env.example file to `REDIS_PASSWORD=`? That way, it's nice and consistent.

**Comment by canoine** [comment]
Done.

**Pull request merged**
