### PR TITLE
Fixed reordering of assets in #7131

### PR DESCRIPTION
**Pull request by lflare**
Fixes issue #7131

Changes in this pull request:

- Simply JSON.stringify-ed payload, and set `Content-Type` header to expected value.

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
`$.ajaxSetup()` also contains the CSRF token which is now no longer used. Are you also getting 500 errors in this branch?

**Comment by lflare** [comment]
> `$.ajaxSetup()` also contains the CSRF token which is now no longer used. Are you also getting 500 errors in this branch?

No I'm not, seems to work just fine?

**Comment by JC5** [comment]
I keep getting 500 errors. Weird.

**Comment by lflare** [comment]
Hmm, well, I'm not able to reproduce your 500s, if you are able to solve it in your PR, feel free to close this one.

**Comment by JC5** [comment]
I merged the other one, but the credits are yours regardless.

**Pull request closed without merging**
