### PR TITLE
Make error pages translatable

### PR DESCRIPTION
**Pull request by sephrat**
I could not find a way to test 500 and 503 error pages.

### CODE REVIEW

**Comment by JC5** [comment]
Browse to /error to test those. I’ll review later :)

**Comment by sephrat** [comment]
> Browse to /error to test those.

/error does show FireflyException.twig, but how do I test 500 and 503 ? I tried /error/500 but this gives a 404.

**Comment by JC5** [comment]
Mmmm. I'm just not sure of uncaught errors (which would cause the 500).

The 503 can be tested, I just realised, by turning on maintenance mode. `php artisan maintenance on` I think it is.

**Comment by sephrat** [comment]
Right, I managed to test 503 with `php artisan down`. Thanks.
Will try to break things to get that 500 error page. Fun fact: if you throw an Exception in FireflyException.twig you get an infinite loop. :-)

**Comment by JC5** [comment]
Nice! I've written down the infinite loop. Just to see if I can catch it somehow.

**Comment by JC5** [comment]
Merged :+1:

**Pull request merged**
