### PR TITLE
UTF8 locale support for Windows

### PR DESCRIPTION
**Pull request by sephrat**
Saw #3519 and noticed it still didn't fix my Windows 10 dev system: special characters were displayed as �
With this change it's all good. Tested with French, Russian and Polish.
This is the result of my personal research but the condition comes from PHP documentation: https://www.php.net/manual/en/function.strftime.php example number 3.

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Which characters are displayed badly, *exactly*? Is it in dates, translated strings or something else?

The PHP_OS thing is a hack i really dislike.

**Comment by sephrat** [comment]
It is in dates:
image
image

Yeah I know it's dirty but it's even used by Carbon which is what I bumped into while debugging this.
image
(basically the snippet from PHP doc)

It's either this or we add the "-" variant on top of "_" to the array returned by getlocaleArray. I don't really mind.

**Comment by sephrat** [comment]
Basically any UTF8 character will be displayed with �. In my previous example, it should write "août" instead of "ao�t".
Russian months are only made of � in current develop branch.

**Comment by JC5** [comment]
Check, which means it's in the locales generated by PHP, not the translations.

**Comment by JC5** [comment]
I'll take the array over the if-statement, at least my code will be cleaner for it.

**Comment by sephrat** [comment]
Yeah the translations are fine.
No problem, go ahead.

**Comment by JC5** [comment]
Thanks again!

**Comment by sephrat** [comment]
Welcome. Ping me if you need a tester after your change.

**Comment by sephrat** [comment]
Just noticed an issue in my fix: it doesn't work when locale is "equal" because of the return statement just before my code. We need to address that case too. Can I leave it up to you since you plan on reworking the condition?

**Comment by JC5** [comment]
I'll pick it up, thx for the headsup!

**Pull request merged**
