### PR TITLE
AppendHash specific for handling duplicate CSV entries

### PR DESCRIPTION
**Pull request by viraptor**
Fixes issue #2353

Changes in this pull request:

- Add an AppendHash specific
- It appends an artificial hash column to the CSV imports, which can be used as External ID
- It allows duplicate transactions from a single import, but will also prevent re-importing the same entries from multiple runs (each time hashes are based only on the row contents + duplicate counter)

(This is in WIP stage, I'll sort out the documentation and strings if you think the idea itself is acceptable)

@JC5

### CODE REVIEW

**Comment by viraptor** [comment]
@JC5 Is this approach ok? Should I polish the PR for merging?

**Comment by JC5** [comment]
I'm going to postpone this until after the next release, so stay tuned. I only noticed the copyright statement isn't yet in your name.

**Comment by viraptor** [comment]
Step away, bot

**Comment by JC5** [comment]
I'll mark it as a bug. That keeps the bot away. I might take the code into a new project as per the roadmap though.

**Comment by JC5** [comment]
The code has been merged with the new CSV importer here:

https://github.com/JC5/firefly-iii-csv-importer

I'm going to let this one be closed by the bot, and pick up these improvements in the new CSV import routine. For more info, see also: https://www.patreon.com/posts/30012174

**Pull request closed without merging**
