### PR TITLE
allow sftp host as backing storage using env

### LINKED ISSUE #1727: Allow for different backing storage in Firefly
**Description**
Please describe your feature request:

As a Heroku user, I would like Firefly III to be able to save files (import/export/attachments/logs) in different storage locations. This is important because Heroku has ephemeral filesystem.
Read more at: https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

I would prefer to use off-site SFTP or FTP (in that order). 

**Solution**
Describe what your feature would add to Firefly III.

Ability to persist uploaded files after dyno restart.

**What are alternatives?**
Please describe what alternatives currently exist.

I've researched a few:
1) No additional packages: Laravel supports the FTP adapter for storage.
in this option we just edit https://github.com/firefly-iii/firefly-iii/blob/d49a13b0916c6c9ae065bacf8471e95c67877edc/config/filesystems.php#L73-L80
to use ftp driver (with its configuration from environment, if such available).
I envision in this case some `if`-s before the `return` , or some ugly ternary inside the return to get this right.

2) Use fallback driver - requires https://github.com/Litipk/flysystem-fallback-adapter
Allows to fallback to to remote storage if not available locally. Not exactly what we want, because writes are only local, and we need to provide a service provider for Laravel (too lazy for that).

3) Use:
* https://github.com/danhunsaker/laravel-flysystem-others
* https://github.com/Litipk/flysystem-fallback-adapter
* https://github.com/thephpleague/flysystem-replicate-adapter
* https://github.com/thephpleague/flysystem-sftp
First of all first package registers with Laravel different service providers (if available, after including in composer.json).
Second of all it provides the 'Mirror' meta-adapter which combines fallback adapter (mentioned before), and replicate adapter to fallback on reads, and also to distribute writes.
https://github.com/danhunsaker/laravel-flysystem-others/blob/43c5e3bf8cbb9bc22a2e228cb644882f0be52f29/config/filesystems.php#L297-L300
Third, and last, this opens up the possibility to easily use wide range of backing storage in the future (like Dropbox, for example).
https://github.com/danhunsaker/laravel-flysystem-others/blob/43c5e3bf8cbb9bc22a2e228cb644882f0be52f29/config/filesystems.php#L40-L44

My recommendation is to use the last option, because it's the easiest (drop packages to composer and edit filesystems.php) and allows many options in the future. I'd be happy to implement this with your blessing.

The GUI side is more tricky, but enabling this feature with some environment variables will be easy.
______

In any case, code such as this:
https://github.com/firefly-iii/firefly-iii/blob/bc4ac303e210d63d1c33ff4c515cd61af1dd625a/tests/Unit/Helpers/Attachments/AttachmentHelperTest.php#L59
and
https://github.com/firefly-iii/firefly-iii/blob/bae40e2cbc14a34f67f96db2a3faa9a1b3a39515/app/Export/Exporter/CsvExporter.php#L64
found using https://github.com/firefly-iii/firefly-iii/search?q=storage_path&unscoped_q=storage_path
need to be updated to use the right disk (thru a facade?) rather than to assume its local (I guess that what storage_path does)

@JC5

### PR DESCRIPTION
**Pull request by hamuz**
Fixes #1727 
Changes in this pull request:

- Added SFTP env variables to enable functionality
- SFTP_HOST and SFTP_FIREFLY_ROOT are required to enable

@JC5

### CODE REVIEW

**Comment by hamuz** [comment]
I've typo on line 162 in config/filesystems.php
Should be export_disk, instead of upload_export.
I'd be thankful if you could fix it. With this fix  it should work as intended.

**Comment by JC5** [comment]
Looks good! I like the mirror construction as well.

Instead of `SFTP_FIREFLY_ROOT` however, I would suggest adding `SFTP_EXPORT_PATH` and `SFTP_UPLOAD_PATH`. That gives more flexibility and tells users they need to have those paths available. 

Shall I can merge this and tinker with it?

**Comment by JC5** [comment]
I threw some things around in the config file. Nothing terribly exciting. It should start working once you set the `SFTP_HOST` in your config file. I've "split" the path to the export/upload directory and I've added the private key option. 

I'll expand the other config files as well and then it might already be done! :+1:

**Comment by JC5** [comment]
Also pushed updated config files.

**Pull request merged**
