### PR TITLE
Fixes account notes parsing (Reopen)

### PR DESCRIPTION
**Pull request by okaufmann**
Version: 5.4.1
Relates Issue: https://github.com/firefly-iii/firefly-iii/issues/3823

Error:
```
Argument 1 passed to FireflyIII\Support\Twig\General::FireflyIII\Support\Twig\{closure}() must be of the type string, null given, called in storage/framework/views/twig/6a/6ab16553233dcc8cfc89e313950594326064d2d4ed99b3d52dcd2fd762fd9075.php on line 245
```

**Changes in this pull request:**

- Fixes notes parsing on Account detail view (first should be called as method)

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Nice, merged!

**Comment by okaufmann** [comment]
Can the issue be closed then?

**Comment by JC5** [comment]
I've added some labels marking it as a bug. That way, when other people see it they won't have to report it again. I hope to release 5.4.2 today with this fix (and some others).

**Comment by okaufmann** [comment]
Genius! And also its how you can find the bugs were fixed since the last version for the changelog. Nice 👍

**Pull request merged**
