### PR TITLE
Can have link in success message to the transaction it refers to

### PR DESCRIPTION
**Pull request by david-me**
Fixes # (if relevant)

Changes in this pull request:
Adds option for messages to contain a link (issue #1623), and makes single transactions use that option

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
I was thinking more of something like this (check out the `route()` method)

```php
session()->flash('success', (string)trans('firefly.stored_journal', ['description' => $journal->description]));
session()->flash('success_uri', route('transactions.show', [$journal->id]));
```

And then something like:
```html
{% if session_has('success') %}
  {% if session_has('success_uri') %}
    <a href="{{ session('success_uri') }}">
  {% endif %}
  {{ session('success') }}
  {% if session_has('success_uri') %}
    </a>
  {% endif %}
{% endif %}
```

That way, you'll never have unescaped content in the view and you can keep the existing code (less duplication).

What do you think?

**Comment by david-me** [comment]
Yes, that makes sense, dryer

**Comment by JC5** [comment]
Nice. I’ll merge it tomorrow. Thanks for your work! :+1:

**Comment by david-me** [comment]
Thanks for your feedback/help :)

**Pull request merged**
