### PR TITLE
Use php-intl to format currencies

### PR DESCRIPTION
**Pull request by hoshsadiq**
Currently the php function `number_format` is used to format currencies.
This is problematic as we have to figure out different things for
different currencies ourselves. These formats are determined based on
the libc's locale functions.

The issue arises where an OS doesn't have the proper locales installed,
or, in some cases, it's not supported (see below on multiple issues).

This addresses this issue by using the php-intl extensions to format the
numbers based on the locale. The extension is already a requirement in
`composer.json`. The solution does not rely on `LC_MONETARY` from the
underlying libc (which in Alpine Linux's case, which uses musl, is not
supported as of yet).

This isn't fully working (e.g. the balance on the dashboard doesn't work
properly yet), but I wanted to get your opinion on this first. It's been
a long time since I've done much PHP work so please give me any feedback
you have.

List of issues that are related and would potentially be fixed using
this PR:

- #2298
- #2946
- #3070
- #3306
- #3519

It would be great if you could tell me what different locales are to be
tested and what their expected input/outputs are. I'd be happy to write a
unit test beforehand, and ensure the PR conforms to previous code. I don't
want a whole bunch angry people coming to you telling you how the formatting
is suddenly messed up. I tested this with a couple of a languages, and they
*seem* okay.

### CODE REVIEW

**Comment by JC5** [comment]
Thanks, this is very nice! And a compliment for fixing the tests as well, which are usually old and forgotten. Also by me. 😉 

A list of candidates can be found [in the configuration](https://github.com/firefly-iii/firefly-iii/blob/main/config/firefly.php#L329). 

Let me know how I can help!

**Comment by hoshsadiq** [comment]
@JC5 this should be ready now. I tried my best to get the non-obvious currencies in the test list. Do let me know if there are any issues.

**Comment by hoshsadiq** [comment]
By the way, I'm not really sure what to with the SonarCloud thing. The error doesn't seem to be related to my code changes.

**Comment by JC5** [comment]
No worries. I started with Sonarcloud just recently and it's not yet working as I'd want to.

**Comment by JC5** [comment]
Merged! Thanks a lot for your contribution :+1:

**Comment by hoshsadiq** [comment]
@JC5 By the way, just in case this becomes a burden in the future, `NumberFormatter` uses [Non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) pretty much everywhere. It took me a while to figure this out, so hoping you won't have to do the same in the future. I was thinking of doing a basic `str_replace` but figured that this character is actually better as it prevents a number from spanning to lines when it's at the end of the first line.

**Comment by JC5** [comment]
Yeah that's quite alright. Breaking numbers would be pretty ugly. Thanks for the heads up!

**Comment by JC5** [comment]
I committed some code to make sure negative numbers are displayed correctly. See my commit above this comment.

**Pull request merged**
