### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by JC5**
Enjoy!

### CODE REVIEW

**Comment by kerti** [comment]
@JC5 may I translate to Bahasa Indonesia?

**Comment by JC5** [comment]
Sure thing. I've enabled it in Crowdin!

**Comment by Aquariu** [comment]
It seems I have finished the French translation. Do I have to do anything now to help getting French support into the next version ?

**Comment by JC5** [comment]
They will be included in the next version automatically, and  I have pushed an update to make sure it can be selected by users. I expect a new release this weekend.

**Comment by kerti** [comment]
Thanks @JC5 👍

**Pull request merged**
