### PR TITLE
Fix syntax errors

### PR DESCRIPTION
**Pull request by lucavallerini**
I fixed some syntax errors that I found when installing the latest develop version.

### CODE REVIEW

**Comment by JC5** [comment]
This enforces PHP7.3 compatibility.

**Comment by lucavallerini** [comment]
Sorry but how? I have PHP 7.3 (7.3.9 to be precise) on my machine...

**Comment by JC5** [comment]
In PHP7.3 those extra commas are allowed.

**Comment by lucavallerini** [comment]
I specifically installed PHP7.3 in order to get the develop branch up and running but for some reason Firefly still uses the 7.2, even tough `php -v` returns the 7.3, sorry the PR.

**Pull request closed without merging**
