### PR TITLE
fix links

### PR DESCRIPTION
**Pull request by ChrisCarini**
Fixes issue https://github.com/firefly-iii/firefly-iii/issues/8252

Changes in this pull request:

- Link for self-hosted (self-managed)
- Link for docker

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Sorry, but these links already seem to be correct in the `develop` branch.

https://github.com/firefly-iii/firefly-iii/blob/develop/readme.md

**Comment by ChrisCarini** [comment]
> Sorry, but these links already seem to be correct in the `develop` branch.
> 
> https://github.com/firefly-iii/firefly-iii/blob/develop/readme.md

Odd, it still shows a diff in this PR (which, is based against the `develop` branch). 🤔

**Comment by JC5** [comment]
I know, weird!

**Comment by ChrisCarini** [comment]
Specifically, you fixed it in this commit: https://github.com/firefly-iii/firefly-iii/commit/b2a301bf94e803d4aaefdd08c62e13a5a0198259#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15R131

GitHub must be on holiday :p

**Comment by JC5** [comment]
I guess so lol. Closing this one.

**Comment by ChrisCarini** [comment]
Haha, thanks! So long as the docs are fixed - probably worth closing out https://github.com/firefly-iii/firefly-iii/issues/8252 if you haven't already :)

**Pull request closed without merging**
