### PR TITLE
Fix edge case amount due in liability

### PR DESCRIPTION
**Pull request by tieu1991**
Changes in this pull request:

Update calculation of amount due in liability.

- Case 6 should add usedAmount to decrease debt.
- New Case 8 for debt paid by revenue account (eg. spouse)

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
I'll check it out later. Could you argue the changed case? I'm pretty certain it's accurate.

**Comment by tieu1991** [comment]
Here is a part of the log after I ran this command: php artisan firefly-iii:trigger-credit-recalculation

[2023-10-03 13:33:12] local.DEBUG: [258/259] Processing transaction.
[2023-10-03 13:33:12] local.DEBUG: Left of debt is: -64441.830000000000
[2023-10-03 13:33:12] local.DEBUG: Amount of transaction is 90.000000000000
[2023-10-03 13:33:12] local.DEBUG: Case 6 (withdrawal into debit liability): -64441.830000000000 + 90.000000000000 = -64531.830000000000
[2023-10-03 13:33:12] local.DEBUG: [259/259] Processing transaction.
[2023-10-03 13:33:12] local.DEBUG: Left of debt is: -64531.830000000000
[2023-10-03 13:33:12] local.DEBUG: Amount of transaction is -30.200000000000
[2023-10-03 13:33:12] local.DEBUG: Case X (all other cases): -64531.830000000000 + -30.200000000000 = -64562.030000000000

You can see for the Case 6 in the log the equation is "-64441.830000000000 + 90.000000000000 = result" which should give "result  = -64351.830000000000". But in the log, the result is from "-64441.830000000000 - 90.000000000000" because the operation is subtract instead of add.

**Comment by JC5** [comment]
Testing this on the demo shows the amount due is calculated correctly. The balance increases which is also correct.

**Comment by JC5** [comment]
Mm the balance is positive which is weird.

**Comment by JC5** [comment]
Alright I can't merge the change in case 6. If I do that you get database mismatches because the money is removed from both accounts and that doesn't work.

**Comment by JC5** [comment]
I've been trying all of these cases with a new set of liabilities. Note that I tested this with a change that makes sure that liabilities start with a negative balance in case you owe the amount to somebody else.

Here's a liability with an opening balance of 500. Please note that it's impossible to replicate this unless you run the develop version of Firefly III:

```
Now processing account #262 ("I owe met start amount")
Found opening balance transaction journal #546
Opening balance is valid
Start of debt is "-500.000000000000", so initial left of debt is "500.000000000000"
Debt direction is "debit"
Found 4 transaction(s) to process.
[1/4] Processing transaction.
Left of debt is: 500.000000000000
Transaction type is "Opening balance", so do nothing.
[2/4] Processing transaction.
Left of debt is: 500.000000000000
Amount of transaction is 100.000000000000
Case 6 (withdrawal into debit liability): 500.000000000000 + 100.000000000000 = 400.000000000000
[3/4] Processing transaction.
Left of debt is: 400.000000000000
Amount of transaction is -50.000000000000
Case 7 (deposit away from liability): 400.000000000000 - 50.000000000000 = 450.000000000000
[4/4] Processing transaction.
Left of debt is: 450.000000000000
Amount of transaction is 50.000000000000
Case X (all other cases): 450.000000000000 + -50.000000000000 = 400.000000000000
Done processing account #262 ("I owe met start amount")
```

In the normal version of Firefly III, you can already validate the following. Create an "i owe" liability with no opening amount, but instead create a transfer of 500 from the liability to your main checking account. THEN follow the same routine as above:

```
Now processing account #265 ("I owe zonder start")
Start of debt is "0", so initial left of debt is "0"
Debt direction is "debit"
Found 4 transaction(s) to process.
[1/4] Processing transaction.
Left of debt is: 0
Amount of transaction is -500.000000000000
Case 7 (deposit away from liability): 0 - 500.000000000000 = 500.000000000000
[2/4] Processing transaction.
Left of debt is: 500.000000000000
Amount of transaction is 100.000000000000
Case 6 (withdrawal into debit liability): 500.000000000000 + 100.000000000000 = 400.000000000000
[3/4] Processing transaction.
Left of debt is: 400.000000000000
Amount of transaction is -50.000000000000
Case 7 (deposit away from liability): 400.000000000000 - 50.000000000000 = 450.000000000000
[4/4] Processing transaction.
Left of debt is: 450.000000000000
Amount of transaction is 50.000000000000
Case X (all other cases): 450.000000000000 + -50.000000000000 = 400.000000000000
Done processing account #265 ("I owe zonder start")
```

So you did find a bug, for which you will get the credit of course! But as far as I can tell, I shouldn't merge this patch.

**Comment by tieu1991** [comment]
Yeah you're right, I looked at it and the withdrawal from liability to expense account were inversed. Basically the borrowing of and interest were wrong in my case. So everything was negative and I assumed it was on purpose. So I tried to fixe all the other transactions to keep the amount due in negative. Anyway happy you found the problem. I'll close this pull request then.

**Pull request closed without merging**
