### PR TITLE
Improvements to transactions list on home page

### PR DESCRIPTION
**Pull request by sephrat**
Changes in this pull request:
- Fixes issue #3382
- Started refactoring sign determination (still WIP - not very proud of the signature of signAmount)
- Fixed grouped transfers sum amount being displayed in black instead of blue

@JC5

### CODE REVIEW

**Comment by sephrat** [comment]
Implementation is still not ideal but I believe it's a small step towards cleaner code.
My tests were quite thorough, hope I didn't miss anything:

- tested the home page and admin/links/show/x
- tested split and regular transactions for all kind of transaction, including reconciliation and initial balance

**Comment by JC5** [comment]
Idk, on the whole I'm just not a fan. It can't escape the feeling it's spagetti code to drag the Account object back and forth like this. I have no better solution though.

**Comment by sephrat** [comment]
Yeah I feel you. Trouble is the input format differs so much between all the methods. But it's not really better to copy/paste the same rules everywhere, there are already some rules that were missing here and there that should be fixed with this. 
Maybe the solution would be to fix the amount upstream, somewhere in Model/TransactionJournal. That logic doesn't really belong to Twig.

**Comment by sephrat** [comment]
Oh wait, were you talking about the new Account object being passed from the template? For that I don't see a better solution either. This transfer thing is such an edge case that you need the context of the account.

**Comment by JC5** [comment]
Yeah exactly. To be honest I’d rather drop the feature. But I’ll think about it. This particular list of transactions is pretty unique and over time pages like this one have become... less optimal :wink:

I have time this weekend I’ll mull it over.

**Comment by sephrat** [comment]
Fair enough. I also have an idea for a different approach to this problem, but I'll do some trial and error before expanding my thoughts. :-) 
Should I withdraw the PR to dereference the open issue? 
Would you like me to submit another PR with just the refactoring part? Basically drop signAmountFromAccountPOV but keep signAmount?
There's also item #3 on my list that we can keep.

**Comment by sephrat** [comment]
OK I've reverted the new feature but kept the refactoring part. It's still probably worth a major refactoring to allow new features, but I hope it's better than before.

**Pull request merged**
