### PR TITLE
Change default database in example environment file 

### PR DESCRIPTION
**Pull request by leander091**
Fixes issue #3476

Changes in this pull request:

- Switch the example environment file to Postgres to ensure consistency with the current docker image and documentation. 

It prevents error like: #3476

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
I'm migrating the default Firefly III configuration to MySQL. This is already the case in the `develop` branch but the main branch still refers to Postgres. The documentation also points to the main branch so people shouldn't find this file unless they look for it themselves.

**Comment by leander091** [comment]
Alright, But i think this is still necessary for now.

The master branch has already the config for MySQL included in the example environment file.  See commit d493820cc82460749b9a531026edaed9e1caa2ce . So this breaks each new install when using docker compose.

**Comment by JC5** [comment]
Crap. I thought I fixed that. I'm gonna push to master instead. Thanks for the headsup.

**Comment by leander091** [comment]
No problem at all :)

**Pull request closed without merging**
