### PR TITLE
Make database connection configurable for docker

### PR DESCRIPTION
**Pull request by janLo**
This adds the option to configure DB_CONNECTION and DB_PORT via docker
env variables, so the usage of the Image is not limited to mysql.

### CODE REVIEW

**Comment by JC5** [comment]
This has been suggested before, but will not be implemented. Please see https://github.com/firefly-iii/firefly-iii/pull/1254 and https://github.com/firefly-iii/firefly-iii/pull/1184 for a discussion about this.

**Comment by janLo** [comment]
Well, I think thats completely the wrong direction. My usecase is not sqlite at all, I just want to use a postgres instance that I have already running. If you want to prevent prevent people from using sqlite, then write it in the docs and/or test that the option contains a valid value on container startup.

Now I'm not able to use the official docker image because of this. Thank you.

**Comment by JC5** [comment]
That last one is something I hadn't even thought about. I'll pick it up!

Most users I have had surrounding Docker so far are newbies. Not implying you are one of course, but these users need guidance most of all. So disabling all of these options makes it easier for me to do support. 

But indeed, this breaks the image for users who _do_ know what they are talking about. A solution is coming. If you know what would be the best way to forcibly disable sqlite, I am all ears.

**Comment by JC5** [comment]
Hi @janLo. I've pushed the change you suggested, together with a big fat warning for users that decide to use "sqlite" as a connection string. I hope this will allow you to use the official docker image again.

The new release should be live end of the month. I apologize for being stubborn.

**Comment by janLo** [comment]
Yes, this works for me. Thank you and sorry for the late reply.

**Pull request closed without merging**
