### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by JC5**
Enjoy!

### CODE REVIEW

**Comment by Aquariu** [comment]
It seems I'm done with the French help pages, too.
I'm sorry to have missed the 4.6.7 deadline, though. I'm happy to have contributed something to your project!

**Comment by JC5** [comment]
Hey @Aquariu, no problem! :D. After all, I did not tell you about the deadline ;). It will be merged into the next release so no harm done. Thanks for your contributions, I appreciate them!

**Comment by Aquariu** [comment]
I got a question for translation:
Now that I'm using the French version (reconfigured the system's locale to fr_FR@UTF-8 also), I see that some of my translations were either a bit off or just plain wrong (out of context). If I update the translations in Crowndin, will they automatically be included in the next release ? I'd like to correct my mistakes if possible.

Kind regards,

**Comment by JC5** [comment]
Yes, they will. You can see the "pull request" updating slowly but surely. I appreciate your efforts, thanks :+1: :grin:

**Pull request merged**
