### PR TITLE
Upgrade Docker container to 4.6.5

### PR DESCRIPTION
**Pull request by ms32035**
Looks like this has been missed

### CODE REVIEW

**Comment by JC5** [comment]
Hey man, thanks for the commit! I knew I forgot something. Unfortunately, I can't update the master branch. Could you edit your commit so it goes to the develop branch?

**Comment by ms32035** [comment]
Now it has conflicts as the docker container in develop is built with COPY from the repo. Besides, when the next version is released, this will have to be updated again. What do we do about it?

**Comment by ms32035** [comment]
Yeah, merging this to develop does not make sense

**Comment by JC5** [comment]
Mmm that's true. I'll have to close this and add it to my todo list for the next release. Is that ok?

**Comment by ms32035** [comment]
sure.

**Pull request closed without merging**
