### PR TITLE
Fixed amountPerPeriod not respecting bill skips

### PR DESCRIPTION
**Pull request by Aethiran**
Changes in this pull request:
- Interface bills overview did not show expected monthy costs correctly (skips were ignored)
- amountPerPeriod() has been adapted to include skips

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
I like it, but this is a terrible way to cast to string: `''.($bill['skip'] + 1)`. Why not use `(string)`?

**Comment by Aethiran** [comment]
Ah true, I will change chat

**Comment by Aethiran** [comment]
*that

**Comment by JC5** [comment]
Smart stuff. Merged!

**Pull request merged**
