### PR TITLE
Replace strtolower to mb_strtolower

### PR DESCRIPTION
**Pull request by kiv06041992**
Fixes issue # (if relevant)

Changes in this pull request:

- Replace strtolower to mb_strtolower in Bill\CreateController@create. Without this changing I was not able to choose frequency repeating of bill.

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
1. What error do you get?
2. What language are you using Firefly III in?

**Comment by kiv06041992** [comment]
1. I did not see any options
2. Russian
It is strange but now I can not repeat bug
Before it look like [img](https://sun9-66.userapi.com/impg/1YgkpEd6O3NMz24tJ60_S4s2kGfIOL6Xi3SYfg/CK48Ryyoc84.jpg?size=1280x642&quality=96&sign=6361029bb44a3aad3da7f7e60dc3534e&type=album)
On the top is `echo $periods[$current]` from Bill\CreateController@create

Anyway strtolower does not work with mb_string

**Comment by JC5** [comment]
I have made a note to replace all `strtolower` code. It does not work well with all languages, one among them Russian. Can I close this PR?

**Comment by kiv06041992** [comment]
Thanks
It will be batter than my commit
You can close my PR

**Pull request closed without merging**
