### PR TITLE
Attempt to add `external_url` filtering support

### PR DESCRIPTION
**Pull request by GeorgeHahn**
Related to https://github.com/firefly-iii/firefly-iii/issues/5606 / https://github.com/firefly-iii/firefly-iii/issues/5326 / https://github.com/firefly-iii/firefly-iii/issues/4903

Changes in this pull request:

- Adds rules/search support for presence/absence of the `external_url` field.

Todo:
- [ ] Set up a local dev environment and test this out.

@JC5 Are you open to this change?

### CODE REVIEW

**Comment by JC5** [comment]
Nice. I'd say "transaction has any external URL". Otherwise, seems to look good already. I'll pull the PR later and check it out.

**Comment by JC5** [comment]
In its current form, it seems to skip over any transaction that doesn't have the external_url meta data value.

The `no_external_url:true` operator finds nothing, because there are no entries where the name is external_url but the value is empty. Likewise, if they do have the external_url, its never empty.

I solved it with this query. I'm not sure if i can push to your branch.

```php
    /**
     * @inheritDoc
     */
    public function withoutExternalUrl(): GroupCollectorInterface
    {
        if (false === $this->hasJoinedMetaTables) {
            $this->hasJoinedMetaTables = true;
            $this->query->leftJoin('journal_meta', 'transaction_journals.id', '=', 'journal_meta.transaction_journal_id');
        }
        $this->query->where(function(Builder $q1) {
            $q1->where(function(Builder $q2) {
                $q2->where('journal_meta.name', '=', 'external_url');
                $q2->whereNull('journal_meta.data');
            })->orWhereNull('journal_meta.name');
        });


        return $this;
    }
```

The `any_external_url` filter is working as expected.

Since the search uses the exact same operators, you can easily test it over there. To that end, add two translations to `firefly.php` (you know which one):

```php
    'search_modifier_no_external_url'                     => 'The transaction has no external URL',
    'search_modifier_any_external_url'                    => 'The transaction must have a (any) external URL',
```

I'm not sure if the grammar rules make it "a" or "an" in this case.

**Comment by GeorgeHahn** [comment]
@JC5 I was worried about that query; thanks for the fix. I pushed your solution & the search strings.

I'm having some trouble getting the app running in a devcontainer. Are you happy with the testing you did or should I spend some time to test this out another day?

**Comment by JC5** [comment]
It looks good to me, I'll merge later today and pick up the translations etc.

**Comment by JC5** [comment]
Merged :+1:

**Pull request merged**
