### PR TITLE
Remove nesting level for markdown

### PR DESCRIPTION
**Pull request by JeroenED**
This PR fixes issue #8956.

Changes in this pull request:
* Removes the markdown nesting level

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
I'm not going to make it unlimited.

**Comment by JC5** [comment]
Sorry, that was a very short reply, lol. Could you change it from 3 to 5? Then I can merge it.

**Comment by JeroenED** [comment]
Here you go. :)

**Comment by JC5** [comment]
:+1:

**Pull request merged**
