### PR TITLE
Replace i tag with em to fix minor issues in Sonar

### PR DESCRIPTION
**Pull request by hamza-fadil**
Fixes issue # (if relevant)
Hello,

It's not much, but I replaced all < i > tags that were marked as minor issue in SonarCloud.

https://sonarcloud.io/project/issues?id=firefly-iii_firefly-iii&resolved=false&rules=Web%3ABoldAndItalicTagsCheck&severities=MINOR&types=BUG

Changes in this pull request:

- Replace <i> tag with em to fix minor issues in Sonar

@JC5

### CODE REVIEW

**Comment by JC5** [comment]
Those are icons, they need that specific tag.

**Comment by JC5** [comment]
Ah no, I am wrong. But if you want to do this right, replace i with span, not em. It's not about text being italics, it's about having a placeholder for the icons.

Could you update your PR? I'll happily merge!

https://stackoverflow.com/questions/40264695/font-awesome-accessibility-issue-use-em-tags-instead-of-i

**Comment by hamza-fadil** [comment]
Hello James, 

I updated the PR to use span instead of em.
Hopefully this fixes the minor issues in Sonar.

Thank you !

**Comment by JC5** [comment]
👍🏻 !

**Pull request merged**
